# Generated by Django 3.0.8 on 2020-07-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=35, null=True)),
                ('c_pay', models.IntegerField(blank=True, null=True)),
                ('c_order', models.TextField(blank=True, null=True)),
                ('c_discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
